# Generated by Django 5.0.7 on 2024-07-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeBook', '0002_recipe_cover_recipe_todos_alter_comment_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='todos',
        ),
        migrations.CreateModel(
            name='CookingSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=250)),
                ('step_no', models.IntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooking_steps', to='RecipeBook.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='RecipeBook.recipe')),
            ],
        ),
    ]
